mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: '127.0.0.1:9090'

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - system
  fallback: []
